- name: Create directories
  file:
    path: functional-tests-files
    state: directory
    owner: jenkins
    group: jenkins
- name: Copy Test Script File
  copy:
    src: "{{ source_name }}/ft_question_questionset_{{ file_version }}.json"
    dest: functional-tests-files/ft_question_questionset_{{ file_version }}.json
- name: Template Env File
  template:
    src: "{{ source_name }}/env_question_questionset_{{ file_version }}.json"
    dest: functional-tests-files/env_question_questionset_{{ file_version }}.json
- name: Trigger Functional Test 
  shell:
    cmd: source /var/lib/jenkins/.nvm/nvm.sh && nvm use 16.19.0 &&  newman run ft_question_questionset_{{ file_version }}.json -e env_question_questionset_{{ file_version }}.json --reporters cli,htmlextra,junit --reporter-htmlextra-export newman/report.html --reporter-junit-export newman/junit_report.xml;
    chdir: functional-tests-files
